import { forwardRef, useImperativeHandle, useState } from 'react';
import { BiTestTube } from 'react-icons/bi';
import { Trash2 } from 'lucide-react';
import type { PreparationModuleHandle } from '../../../../../core/preparation/ui/PreparationModuleHandle';
import type { PreparationAttachedFile } from '../../../../../core/preparation-engine/components/FileAttachmentSection';
import SamplePreparationSection from '../../../../../core/preparation-engine/components/SamplePreparationSection';
import FileAttachmentSection from '../../../../../core/preparation-engine/components/FileAttachmentSection';
import PreparationCompleteSection from '../../../../../core/preparation-engine/components/PreparationCompleteSection';
import PreparationCompleteModal from '../../../../../core/preparation-engine/components/PreparationCompleteModal';
import UnlockPreparationDialog from '../../../../../core/preparation-engine/components/UnlockPreparationDialog';
import PreparationToast from '../../../../../core/preparation-engine/components/PreparationToast';
import type { SamplePreparationLithosun300, SamplePreparationLithosun300Step } from '../models/SamplePreparationLithosun300';
import type { Lithosun300ModuleData, Lithosun300ModuleDraft } from '../models';
import type { CalculationLithosun300 } from '../models/CalculationLithosun300';
import { createCalculationLithosun300, createSamplePreparationLithosun300, restoreCalculationLithosun300, restoreSamplePreparationLithosun300 } from '../factory';
import Lithosun300CalculationSection from './Lithosun300CalculationSection';

export interface Lithosun300PreparationModuleProps { preparationId: string; parameterId: number; parameterName?: string | null; parameterCode?: string | null; role: string; isLocked: boolean; canUnlockPreparation?: boolean; canEditCalculations?: boolean; onLockPreparation: (parameterId: number) => void; onUnlockPreparation: (parameterId: number) => void; }
const parseSteps = (v: unknown): SamplePreparationLithosun300Step[] => { if (Array.isArray(v)) return v as SamplePreparationLithosun300Step[]; if (typeof v !== 'string') return []; try { const p = JSON.parse(v); return Array.isArray(p) ? p as SamplePreparationLithosun300Step[] : []; } catch { return []; } };
const normalizeDate = (v: unknown) => typeof v === 'string' && v.trim() ? v : null;

function PrepCard({ preparation, disabled, onChange, onRemove }: { preparation: SamplePreparationLithosun300; disabled: boolean; onChange: (i: number, field: keyof SamplePreparationLithosun300Step, value: string) => void; onRemove: () => void; }) {
 return <div className="mb-4 overflow-hidden rounded-lg border border-emerald-200 bg-white"><div className="flex items-center justify-between bg-gradient-to-r from-emerald-700 via-emerald-800 to-slate-900 px-4 py-3 text-white"><div><div className="font-semibold">{preparation.label}</div><div className="text-xs text-emerald-100">Lithosun 300 tablet inputs</div></div><button type="button" disabled={disabled} onClick={onRemove} className="disabled:opacity-40"><Trash2 className="h-4 w-4"/></button></div><div className="space-y-3 bg-gradient-to-br from-emerald-50/50 to-slate-50/30 p-5">{preparation.steps.map((s,i) => <div key={`${preparation.id}-${i}`} className="grid items-center gap-3 rounded-lg border border-emerald-200 bg-white p-3 md:grid-cols-[minmax(0,1fr)_220px_70px]"><label className="text-sm font-semibold text-emerald-900">{s.name}</label><input disabled={disabled} value={s.value1 ?? ''} onChange={e => onChange(i, 'value1', e.target.value)} inputMode="decimal" className="rounded-lg border border-emerald-300 px-3 py-2 text-sm focus:border-emerald-500 focus:outline-none" placeholder="Enter value"/><span className="text-xs font-semibold text-slate-500">{s.unit1 || '—'}</span></div>)}</div></div>;
}

const Lithosun300PreparationModule = forwardRef<PreparationModuleHandle<Lithosun300ModuleDraft, unknown>, Lithosun300PreparationModuleProps>((props, ref) => {
 const { parameterId, parameterName, parameterCode, isLocked, canUnlockPreparation = false, canEditCalculations = false, onLockPreparation, onUnlockPreparation } = props;
 const [samplePreparations, setSamplePreparations] = useState<SamplePreparationLithosun300[]>([]);
 const [files, setFiles] = useState<PreparationAttachedFile[]>([]);
 const [calculations, setCalculations] = useState<CalculationLithosun300[]>([]);
 const [completed, setCompleted] = useState(false); const [completedAt, setCompletedAt] = useState<string | null>(null); const [showComplete, setShowComplete] = useState(false); const [showUnlock, setShowUnlock] = useState(false); const [unlocking, setUnlocking] = useState(false);
 const [toast, setToast] = useState<{visible:boolean;message:string;type:'success'|'error'|'info'}>({visible:false,message:'',type:'success'});
 const locked = isLocked || completed; const notify = (message: string, type: 'success'|'error'|'info' = 'success') => setToast({visible:true,message,type});
 const addPreparation = () => { if (locked) return; setSamplePreparations(v => [...v, createSamplePreparationLithosun300(v.length)]); notify('Lithosun 300 sample preparation added.'); };
 const removePreparation = (index: number) => { if (locked) return; setSamplePreparations(v => v.filter((_,i) => i !== index).map((p,i) => ({...p,id:i+1,label:`Sample Preparation ${i+1}`}))); };
 const updateStep = (pi:number, si:number, field:keyof SamplePreparationLithosun300Step, value:string) => { if (locked) return; setSamplePreparations(v => v.map((p,i) => i !== pi ? p : {...p,steps:p.steps.map((s,j) => j !== si ? s : {...s,[field]:value})})); setCalculations(v => v.map(c => ({...c,results:[null,null,null,null,null,null]}))); };
 const addFiles = async (selected: File[]) => { if (locked) return; const mapped: PreparationAttachedFile[] = []; for (const file of selected.slice(0, Math.max(0,10-files.length))) { if (file.type !== 'application/pdf' && !file.name.toLowerCase().endsWith('.pdf')) { notify(`${file.name} is not a PDF.`, 'error'); continue; } const base64 = await new Promise<string>((resolve,reject) => { const r = new FileReader(); r.onload = () => resolve(String(r.result ?? '')); r.onerror = reject; r.readAsDataURL(file); }); mapped.push({id:`${Date.now()}-${mapped.length}`,name:file.name,size:file.size,type:file.type,fileDataBase64:base64}); } if (mapped.length) setFiles(v => [...v,...mapped]); };
 const complete = () => { if (isLocked || !samplePreparations.length) return; const now = new Date().toISOString(); setCompleted(true); setCompletedAt(now); setShowComplete(false); onLockPreparation(parameterId); notify('Lithosun 300 preparation marked as complete!'); };
 const unlock = async () => { if (!canUnlockPreparation) return; setUnlocking(true); try { setCompleted(false); setCompletedAt(null); onUnlockPreparation(parameterId); setShowUnlock(false); notify('Lithosun 300 preparation unlocked successfully.'); } finally { setUnlocking(false); } };
 useImperativeHandle(ref, () => ({ getDraft: () => ({samplePreparations,files,calculations,completed,completedAt}), loadDraft: draft => { if (!draft || typeof draft !== 'object') return; const v = draft as Partial<Lithosun300ModuleData>; setSamplePreparations(Array.isArray(v.samplePreparations) ? v.samplePreparations.map((p,i) => restoreSamplePreparationLithosun300(p,i)) : []); setFiles(Array.isArray(v.files) ? v.files : []); setCalculations(Array.isArray(v.calculations) ? v.calculations.map((c,i) => restoreCalculationLithosun300(c,i)) : []); setCompleted(Boolean(v.completed)); setCompletedAt(normalizeDate(v.completedAt)); }, restoreFromWorksheet: async worksheet => { if (!worksheet || typeof worksheet !== 'object') return; const w = worksheet as {preparations?:unknown[];calculations?:unknown[];files?:unknown[];preparationCompletedAt?:unknown}; const ps = (w.preparations ?? []).filter(x => { const v = x as Record<string,unknown>; return String(v.preparationType ?? '').toLowerCase() === 'lithosun300'; }).map((x,i) => { const v = x as Record<string,unknown>; return restoreSamplePreparationLithosun300({...v,steps:parseSteps(v.steps)},i); }); const cs = (w.calculations ?? []).filter(x => String((x as Record<string,unknown>).calculationType ?? '').toLowerCase() === 'lithosun300').map((x,i) => { const v = x as Record<string,unknown>; let data: unknown = v.data; if (typeof data === 'string') { try { data = JSON.parse(data); } catch { data = {}; } } return restoreCalculationLithosun300(data ?? v,i); }); setSamplePreparations(ps); setCalculations(cs); setFiles([]); setCompleted(Boolean(w.preparationCompletedAt)); setCompletedAt(normalizeDate(w.preparationCompletedAt)); }}), [samplePreparations,files,calculations,completed,completedAt]);
 return <div className="mt-8 overflow-hidden rounded-3xl border border-emerald-200 bg-gradient-to-br from-white via-emerald-50/30 to-white pb-8 shadow-2xl"><div className="bg-gradient-to-r from-white via-white to-emerald-50 px-6 py-5"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-emerald-700 to-emerald-900"><BiTestTube className="h-5 w-5 text-white"/></div><div><h2 className="text-2xl font-bold text-emerald-900">Lithosun 300 Analysis</h2><p className="text-sm text-emerald-600">Metal Laboratory • Tablets & Dissolution</p></div></div><div className="rounded-full bg-emerald-100 px-5 py-2 text-sm font-semibold text-emerald-700">{samplePreparations.length} Preparations</div></div></div><SamplePreparationSection title="Calculation for Tablets" preparations={samplePreparations} isLocked={locked} onAddPreparation={addPreparation} onRemovePreparation={(_,i) => removePreparation(i)} renderPreparation={(p,i) => <PrepCard preparation={p} disabled={locked} onRemove={() => removePreparation(i)} onChange={(si,f,v) => updateStep(i,si,f,v)}/>}/>{samplePreparations.length > 0 && <><div className="mx-6 mb-6"><FileAttachmentSection files={files} isLocked={locked} title="Attach Lithosun 300 Preparation Files (PDF)" maxFiles={10} onAttachFiles={addFiles} onRemoveFile={(_,i) => setFiles(v => v.filter((__,j) => j !== i))}/></div><div className="mx-6"><PreparationCompleteSection preparationName="Lithosun 300" isCompleted={completed} isLocked={locked} completedAt={completedAt} canUnlockPreparation={canUnlockPreparation} onComplete={() => setShowComplete(true)} onUnlock={() => setShowUnlock(true)}/></div>{completed && <Lithosun300CalculationSection calculations={calculations} samplePreparations={samplePreparations} canEditCalculations={canEditCalculations} onAdd={() => setCalculations(v => [...v,createCalculationLithosun300(v.length)])} onRemove={id => setCalculations(v => v.filter(c => c.id !== id))} onUpdate={c => setCalculations(v => v.map(x => x.id === c.id ? c : x))}/>}<PreparationCompleteModal isOpen={showComplete} preparationName="Lithosun 300" parameterName={parameterName} parameterCode={parameterCode} onConfirm={complete} onCancel={() => setShowComplete(false)}/><UnlockPreparationDialog isOpen={showUnlock} isUnlocking={unlocking} parameterName={parameterName ?? ''} parameterCode={parameterCode ?? ''} onClose={() => setShowUnlock(false)} onConfirm={unlock}/></>}<PreparationToast visible={toast.visible} type={toast.type} message={toast.message} onClose={() => setToast(v => ({...v,visible:false}))}/></div>;
});
Lithosun300PreparationModule.displayName = 'Lithosun300PreparationModule';
export default Lithosun300PreparationModule;
