import { Calculator } from 'lucide-react';
import type { CalculationLithosun300 } from '../models/CalculationLithosun300';
import type { SamplePreparationLithosun300 } from '../models/SamplePreparationLithosun300';
import CalculationDetailLithosun300 from './CalculationDetailLithosun300';

interface Props { calculations: CalculationLithosun300[]; samplePreparations: SamplePreparationLithosun300[]; canEditCalculations: boolean; onAdd: () => void; onRemove: (id: number) => void; onUpdate: (value: CalculationLithosun300) => void; }
export default function Lithosun300CalculationSection({ calculations, samplePreparations, canEditCalculations, onAdd, onRemove, onUpdate }: Props) {
 return <section className="mt-8 pb-10"><div className="mx-6 flex items-center gap-4 py-2"><div className="h-px flex-1 bg-gradient-to-r from-transparent via-emerald-300 to-transparent"/><div className="rounded-lg border border-emerald-300/50 bg-emerald-100 px-4 py-2 text-xs font-bold uppercase tracking-wider text-emerald-800">CALCULATIONS</div><div className="h-px flex-1 bg-gradient-to-r from-transparent via-emerald-300 to-transparent"/></div><div className="mx-6 rounded-2xl border border-emerald-200 bg-white/70 p-6 shadow-lg"><div className="mb-6 flex items-center justify-between"><h3 className="flex items-center gap-3 text-lg font-bold text-emerald-900"><span className="h-6 w-1.5 rounded-full bg-gradient-to-b from-emerald-600 to-emerald-900"/>Lithosun 300 Dissolution Calculation</h3><button type="button" disabled={!canEditCalculations} onClick={onAdd} className="rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">+ Add Calculation</button></div>{calculations.length === 0 ? <div className="rounded-xl border-2 border-dashed border-emerald-300 py-12 text-center"><Calculator className="mx-auto h-10 w-10 text-emerald-400"/><p className="mt-3 font-semibold text-emerald-800">No Lithosun 300 calculations added yet</p></div> : <div className="space-y-6">{calculations.map(c => <CalculationDetailLithosun300 key={c.id} calculation={c} samplePreparations={samplePreparations} isLocked={!canEditCalculations} onRemove={() => onRemove(c.id)} onUpdate={onUpdate}/>)}</div>}</div></section>;
}
