import React, { useMemo, useState } from "react";
import { Calculator, ChevronDown, ChevronUp, Trash2 } from "lucide-react";
import CustomDropdown from "../../../../../shared/CustomDropdown";
import type { CalculationZptoShampoo } from "../models/CalculationZptoShampoo";
import type { SamplePreparationZptoShampoo } from "../models/SamplePreparationZptoShampoo";
import { calculateZptoShampoo } from "../calculation";

type Props = { calculation: CalculationZptoShampoo; samplePreparations: SamplePreparationZptoShampoo[]; onUpdate:(c:CalculationZptoShampoo)=>void; onRemove:()=>void; isLocked:boolean; };
const text=(v:unknown)=>v===null||v===undefined?"":String(v);
const num=(v:unknown)=>{const s=text(v).trim(); if(!s)return null; const n=Number(s); return Number.isFinite(n)?n:null;};
const step=(p:SamplePreparationZptoShampoo|null,name:string)=>p?.steps.find(s=>s.name===name);
const calculateSpecificGravity=(w1:unknown,w2:unknown,w3:unknown)=>{const a=num(w1),b=num(w2),c=num(w3);if(a===null||b===null||c===null||a===c)return null;const v=((a-b)/(a-c))*0.998;return Number.isFinite(v)?Number(v.toFixed(5)):null;};
const ZptoShampooCalculationDetail:React.FC<Props>=({calculation,samplePreparations,onUpdate,onRemove,isLocked})=>{
 const [expanded,setExpanded]=useState(true);
 const selected=useMemo(()=>samplePreparations.find(p=>p.label===calculation.selectedSamplePreparationLabel)??null,[samplePreparations,calculation.selectedSamplePreparationLabel]);
 const values=useMemo(()=>{const get=(n:string)=>step(selected,n); const s=get("Instrument Concentration (Sample)"),b=get("Instrument Concentration (Blank)"),sw=get("Sample Weight (SW1)"),v1=get("Volume Makeup (V1)"),v2=get("Dilution Factor 1 (V2)"),w1=get("Weight of Empty Pycnometer (W1)"),w2=get("Weight of Pycnometer with Sample (W2)"),w3=get("Weight of Pycnometer with Water (W3)"),lc=get("Label Claim"),mw=get("Molecular Weight");
 return {sample:s?.value1??"",sampleUnit:s?.unit1??"ppm",blank:b?.value1??"",blankUnit:b?.unit1??"ppm",sw1:sw?.value1??"",sw1Unit:sw?.unit1??"g",v1:v1?.value1??"",v1Unit:v1?.unit1??"ml",v2Factor:v2?.value1??"",v2Volume:v2?.value2??"",v2VolumeUnit:v2?.unit2??"ml",w1:w1?.value1??"",w2:w2?.value2??"",w3:w3?.value2??"",sg:calculateSpecificGravity(w1?.value1,w2?.value2,w3?.value2)??"",lc:lc?.value1??"",mw1:mw?.value1??"",mw2:mw?.value2??""};},[selected]);
 const errors=useMemo(()=>{if(!selected)return ["Please select a Sample Preparation"]; const required:[string,unknown,boolean][]=[["Instrument Concentration (Sample)",values.sample,false],["Instrument Concentration (Blank)",values.blank,false],["Sample Weight",values.sw1,true],["Volume Makeup",values.v1,true],["V2 factor",values.v2Factor,true],["V2 volume",values.v2Volume,true],["W1 (Empty Pycnometer)",values.w1,true],["W2 (Pycnometer with Sample)",values.w2,true],["W3 (Pycnometer with Water)",values.w3,true],["Specific Gravity",values.sg,true],["Molecular Weight (Value 1)",values.mw1,true],["Molecular Weight (Value 2)",values.mw2,true],["Label Claim",values.lc,true]]; return required.flatMap(([label,value,positive])=>{const raw=text(value).trim();if(!raw)return [`${label}: value is required`];const n=num(value);if(n===null)return [`${label}: value must be numeric`];if(positive&&n<=0)return [`${label}: value must be greater than 0`];if(!positive&&n<0)return [`${label}: value cannot be negative`];return [];});},[selected,values]);
 const update=(field:keyof CalculationZptoShampoo,value:CalculationZptoShampoo[typeof field])=>onUpdate({...calculation,[field]:value});
 const calculate=()=>{if(isLocked||errors.length||!selected)return;const r=calculateZptoShampoo({instrumentConcentrationSample:values.sample,instrumentConcentrationSampleUnit:values.sampleUnit,instrumentConcentrationBlank:values.blank,instrumentConcentrationBlankUnit:values.blankUnit,sampleWeight:values.sw1,volumeMakeup:values.v1,dilutionFactor1:values.v2Factor,dilutionVolume1:values.v2Volume,weightEmptyPycnometer:values.w1,weightPycnometerSample:values.w2,weightPycnometerWater:values.w3,specificGravity:values.sg,molecularWeight1:values.mw1,molecularWeight2:values.mw2,labelClaim:values.lc});onUpdate({...calculation,selectedSamplePreparationLabel:selected.label,sw1:values.sw1,sw1Unit:values.sw1Unit,v1:values.v1,v1Unit:values.v1Unit,v2Factor:values.v2Factor,v2Volume:values.v2Volume,v2VolumeUnit:values.v2VolumeUnit,weightEmptyPycnometer:values.w1,weightPycnometerSample:values.w2,weightPycnometerWater:values.w3,specificGravity:values.sg,molecularWeight1:values.mw1,molecularWeight2:values.mw2,labelClaim:values.lc,instrumentConcentrationSample:values.sample,instrumentConcentrationSampleUnit:values.sampleUnit,instrumentConcentrationBlank:values.blank,instrumentConcentrationBlankUnit:values.blankUnit,calculationResult:r.success?r.result:`Error: ${r.error??"Calculation failed"}`,calculationResultUnit:r.success?"% of L.C.":""});};
  const result=num(calculation.calculationResult),min=num(calculation.acceptanceLimitMin),max=num(calculation.acceptanceLimitMax); const pass=result!==null&&!text(calculation.calculationResult).startsWith("Error")&&(min===null||result>=min)&&(max===null||result<=max);
 return <div className="overflow-hidden rounded-xl border-2 border-emerald-200 bg-white shadow-lg">
  <div className="bg-gradient-to-r from-emerald-700 via-emerald-800 to-slate-900"><div className="flex items-center justify-between px-4 py-3 text-white"><button type="button" onClick={()=>setExpanded(v=>!v)} className="flex min-w-0 flex-1 items-center gap-4 text-left"><span className="rounded-lg border border-white/30 bg-white/20 p-2"><Calculator className="h-5 w-5"/></span><span><span className="block text-sm font-semibold">{calculation.label}</span><span className="block text-xs text-emerald-100">ZPTO SHAMPOO</span></span></button><div className="flex gap-2"><button type="button" onClick={()=>setExpanded(v=>!v)} className="rounded-lg p-2 hover:bg-white/20">{expanded?<ChevronUp/>:<ChevronDown/>}</button><button type="button" onClick={onRemove} disabled={isLocked} className="rounded-lg border border-white/30 bg-white/20 p-2 disabled:opacity-40"><Trash2 className="h-4 w-4"/></button></div></div></div>
  {expanded&&<div className="space-y-5 bg-gradient-to-b from-white to-slate-50 p-6">
   <div className="rounded-lg border-2 border-emerald-200 bg-emerald-50 p-4"><label className="mb-2 block text-sm font-bold text-slate-700">Select Sample Preparation</label><CustomDropdown options={samplePreparations.map(p=>({value:p.label,label:p.label}))} value={calculation.selectedSamplePreparationLabel??""} onChange={v=>update("selectedSamplePreparationLabel",v||null)} placeholder="Select sample preparation..." colorScheme="emerald" disabled={isLocked}/></div>
   {selected&&errors.length>0&&<div className="rounded-lg border-2 border-red-200 bg-red-50 px-5 py-4"><h4 className="mb-2 text-sm font-bold text-red-800">Validation Error</h4><ul className="space-y-1">{errors.map(e=><li key={e} className="text-xs text-red-700">• {e}</li>)}</ul></div>}
   {selected&&<div className="rounded-lg border-2 border-emerald-200 bg-white p-4"><h4 className="mb-3 text-sm font-bold text-slate-900">Formula for ZPTO Shampoo (Excel)</h4><div className="rounded bg-slate-50 p-4 text-center font-mono text-xs leading-6"><div className="border-b-2 border-black pb-2">((Sample − Blank) × V1 × V2(volume) × Specific Gravity × MW1 × 100)</div><div className="pt-2">(SW1 × 10,000 × V2(factor) × MW2 × Label Claim)</div></div><p className="mt-2 text-right text-xs font-semibold text-slate-600">= % of L.C.</p></div>}
   {selected&&<div className="rounded-lg border-2 border-emerald-200 bg-emerald-50 p-4"><h5 className="mb-3 text-sm font-bold text-slate-700">Acceptance Limit</h5><div className="grid gap-3 md:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Minimum Limit<input value={text(calculation.acceptanceLimitMin)} disabled={isLocked} onChange={e=>update("acceptanceLimitMin",e.target.value)} className="mt-1 w-full rounded-lg border border-emerald-300 px-3 py-2 text-xs outline-none transition hover:border-emerald-500 focus:border-emerald-500 focus:ring-2 focus:ring-emerald-200"/></label><label className="text-xs font-semibold text-slate-600">Maximum Limit<input value={text(calculation.acceptanceLimitMax)} disabled={isLocked} onChange={e=>update("acceptanceLimitMax",e.target.value)} className="mt-1 w-full rounded-lg border border-emerald-300 px-3 py-2 text-xs outline-none transition hover:border-emerald-500 focus:border-emerald-500 focus:ring-2 focus:ring-emerald-200"/></label></div></div>}
   <div className="flex justify-center"><button type="button" disabled={isLocked||!selected||errors.length>0} onClick={calculate} className="rounded-lg bg-gradient-to-r from-emerald-700 to-slate-900 px-7 py-3 text-sm font-semibold text-white shadow-md disabled:cursor-not-allowed disabled:bg-gray-400 disabled:opacity-50">Calculate Result</button></div>
   {calculation.calculationResult!==null&&<div className="overflow-hidden rounded-lg border-2 border-emerald-300 bg-white shadow-sm"><div className="bg-gradient-to-r from-emerald-700 via-emerald-800 to-slate-900 px-4 py-2"><h6 className="text-sm font-bold text-white">ZPTO SHAMPOO Result</h6></div><div className="flex items-center gap-3 p-4"><p className="text-2xl font-bold text-slate-800">{text(calculation.calculationResult)} <span className="text-sm">{calculation.calculationResultUnit}</span></p>{(()=>{const hasMin=min!==null;const hasMax=max!==null;if(!hasMin&&!hasMax)return null;return <span className={`m-2 inline-block rounded-full border px-3 py-1 text-sm font-bold ${pass?"border-emerald-300 bg-emerald-100 text-emerald-800":"border-red-300 bg-red-100 text-red-800"}`}>{pass?"Pass":"Fail"}</span>;})()}</div></div>}
  </div>}
 </div>;
};
export default ZptoShampooCalculationDetail;
